[project]
name = "mwcli"
version = "0.1.0"
description = "CLI wrapper around mwclient"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "mwclient",
  "html2text",
]

[project.optional-dependencies]
test = [
  "pytest",
]

[project.scripts]
mwcli = "mwcli.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mwcli"]
